# Generated by Django 4.2.23 on 2025-08-20 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeForfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_forfait', models.CharField(max_length=100)),
                ('desc_forfait', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('data_mo', models.IntegerField()),
                ('minutes', models.IntegerField(default=0)),
                ('sms', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duree_jours', models.IntegerField()),
                ('type_forfait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_client.typeforfait')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tel', models.CharField(max_length=13)),
                ('cin', models.CharField(max_length=12)),
                ('date_naissance', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField()),
                ('est_actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_client.client')),
                ('forfait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_client.forfait')),
            ],
        ),
    ]
